authService:
  host: "handshake-auth.sofine.my.id"
  image:
    tag: 44b823d
productService:
  host: "handshake-product.sofine.my.id"
  image:
    tag: e28b09f
orderService:
  host: "handshake-order.sofine.my.id"
  image:
    tag: e28b09f
emailService:
  host: "handshake-email.sofine.my.id"
  image:
    tag: 42a2a5b
frontend:
  host: "handshake.sofine.my.id"
  image:
    tag: 3531a83
