apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: handshake
  labels:
    app: handshake
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/gagahsyuja/handshake-infra.git
    targetRevision: HEAD
    path: apps/
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
