apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "handshake.frontend" . }}
  labels: {{ include "handshake.frontend.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels: {{ include "handshake.frontend.labels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "handshake.frontend.labels" . | nindent 8 }}
      annotations: {{ include "handshake.frontend.vault.annotations" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Release.Namespace | quote }}
      topologySpreadConstraints: {{ include "handshake.topologySpreadConstraints" . | nindent 8 }}
      containers:
        - name: frontend
          image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
          ports:
            - containerPort: {{ template "handshake.frontend.port" . }}
          command: [ "bash", "-c" ]
          args:
            - |
              while [ ! -f /vault/secrets/frontend ]; do
                echo "Waiting for Vault secrets..."
                sleep 2
              done
              source /vault/secrets/frontend
              exec node /app/dist/server/entry.mjs
          livenessProbe:
            httpGet:
              path: /live
              port: {{ template "handshake.frontend.port" . }}
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: {{ template "handshake.frontend.port" . }}
            initialDelaySeconds: 5
            periodSeconds: 5
          resources: {{ include "handshake.frontend.resources" . | nindent 12 }}
