apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "handshake.product" . }}
  labels: {{ include "handshake.product.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: {{ .Values.productService.replicas }}
  selector:
    matchLabels: {{ include "handshake.product.labels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "handshake.product.labels" . | nindent 8 }}
      annotations: {{ include "handshake.product.vault.annotations" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Release.Namespace | quote }}
      topologySpreadConstraints: {{ include "handshake.topologySpreadConstraints" . | nindent 8 }}
      containers:
        - name: product-service
          image: {{ .Values.productService.image.repository }}:{{ .Values.productService.image.tag }}
          ports:
            - containerPort: {{ template "handshake.product.port" . }}
          command: [ "bash", "-c" ]
          args:
            - |
              source /vault/secrets/product
              exec handshake_product
          livenessProbe:
            httpGet:
              path: /live
              port: {{ template "handshake.product.port" . }}
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: {{ template "handshake.product.port" . }}
            initialDelaySeconds: 5
            periodSeconds: 5
          resources: {{ include "handshake.product.resources" . | nindent 12 }}
